/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/kotskinds/apis/kots/v1beta1"
	kotsv1beta1 "github.com/replicatedhq/kotskinds/client/kotsclientset/typed/kots/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeApplications implements ApplicationInterface
type fakeApplications struct {
	*gentype.FakeClientWithList[*v1beta1.Application, *v1beta1.ApplicationList]
	Fake *FakeKotsV1beta1
}

func newFakeApplications(fake *FakeKotsV1beta1, namespace string) kotsv1beta1.ApplicationInterface {
	return &fakeApplications{
		gentype.NewFakeClientWithList[*v1beta1.Application, *v1beta1.ApplicationList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("applications"),
			v1beta1.SchemeGroupVersion.WithKind("Application"),
			func() *v1beta1.Application { return &v1beta1.Application{} },
			func() *v1beta1.ApplicationList { return &v1beta1.ApplicationList{} },
			func(dst, src *v1beta1.ApplicationList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ApplicationList) []*v1beta1.Application { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.ApplicationList, items []*v1beta1.Application) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
