/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	kotsv1beta2 "github.com/replicatedhq/kotskinds/apis/kots/v1beta2"
	scheme "github.com/replicatedhq/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LicensesGetter has a method to return a LicenseInterface.
// A group's client should implement this interface.
type LicensesGetter interface {
	Licenses(namespace string) LicenseInterface
}

// LicenseInterface has methods to work with License resources.
type LicenseInterface interface {
	Create(ctx context.Context, license *kotsv1beta2.License, opts v1.CreateOptions) (*kotsv1beta2.License, error)
	Update(ctx context.Context, license *kotsv1beta2.License, opts v1.UpdateOptions) (*kotsv1beta2.License, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, license *kotsv1beta2.License, opts v1.UpdateOptions) (*kotsv1beta2.License, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kotsv1beta2.License, error)
	List(ctx context.Context, opts v1.ListOptions) (*kotsv1beta2.LicenseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kotsv1beta2.License, err error)
	LicenseExpansion
}

// licenses implements LicenseInterface
type licenses struct {
	*gentype.ClientWithList[*kotsv1beta2.License, *kotsv1beta2.LicenseList]
}

// newLicenses returns a Licenses
func newLicenses(c *KotsV1beta2Client, namespace string) *licenses {
	return &licenses{
		gentype.NewClientWithList[*kotsv1beta2.License, *kotsv1beta2.LicenseList](
			"licenses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kotsv1beta2.License { return &kotsv1beta2.License{} },
			func() *kotsv1beta2.LicenseList { return &kotsv1beta2.LicenseList{} },
		),
	}
}
