/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	kotsv1beta1 "github.com/replicatedhq/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IdentityConfigsGetter has a method to return a IdentityConfigInterface.
// A group's client should implement this interface.
type IdentityConfigsGetter interface {
	IdentityConfigs(namespace string) IdentityConfigInterface
}

// IdentityConfigInterface has methods to work with IdentityConfig resources.
type IdentityConfigInterface interface {
	Create(ctx context.Context, identityConfig *kotsv1beta1.IdentityConfig, opts v1.CreateOptions) (*kotsv1beta1.IdentityConfig, error)
	Update(ctx context.Context, identityConfig *kotsv1beta1.IdentityConfig, opts v1.UpdateOptions) (*kotsv1beta1.IdentityConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, identityConfig *kotsv1beta1.IdentityConfig, opts v1.UpdateOptions) (*kotsv1beta1.IdentityConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kotsv1beta1.IdentityConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*kotsv1beta1.IdentityConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kotsv1beta1.IdentityConfig, err error)
	IdentityConfigExpansion
}

// identityConfigs implements IdentityConfigInterface
type identityConfigs struct {
	*gentype.ClientWithList[*kotsv1beta1.IdentityConfig, *kotsv1beta1.IdentityConfigList]
}

// newIdentityConfigs returns a IdentityConfigs
func newIdentityConfigs(c *KotsV1beta1Client, namespace string) *identityConfigs {
	return &identityConfigs{
		gentype.NewClientWithList[*kotsv1beta1.IdentityConfig, *kotsv1beta1.IdentityConfigList](
			"identityconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kotsv1beta1.IdentityConfig { return &kotsv1beta1.IdentityConfig{} },
			func() *kotsv1beta1.IdentityConfigList { return &kotsv1beta1.IdentityConfigList{} },
		),
	}
}
