/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	kotsv1beta1 "github.com/replicatedhq/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InstallationsGetter has a method to return a InstallationInterface.
// A group's client should implement this interface.
type InstallationsGetter interface {
	Installations(namespace string) InstallationInterface
}

// InstallationInterface has methods to work with Installation resources.
type InstallationInterface interface {
	Create(ctx context.Context, installation *kotsv1beta1.Installation, opts v1.CreateOptions) (*kotsv1beta1.Installation, error)
	Update(ctx context.Context, installation *kotsv1beta1.Installation, opts v1.UpdateOptions) (*kotsv1beta1.Installation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, installation *kotsv1beta1.Installation, opts v1.UpdateOptions) (*kotsv1beta1.Installation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kotsv1beta1.Installation, error)
	List(ctx context.Context, opts v1.ListOptions) (*kotsv1beta1.InstallationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kotsv1beta1.Installation, err error)
	InstallationExpansion
}

// installations implements InstallationInterface
type installations struct {
	*gentype.ClientWithList[*kotsv1beta1.Installation, *kotsv1beta1.InstallationList]
}

// newInstallations returns a Installations
func newInstallations(c *KotsV1beta1Client, namespace string) *installations {
	return &installations{
		gentype.NewClientWithList[*kotsv1beta1.Installation, *kotsv1beta1.InstallationList](
			"installations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kotsv1beta1.Installation { return &kotsv1beta1.Installation{} },
			func() *kotsv1beta1.InstallationList { return &kotsv1beta1.InstallationList{} },
		),
	}
}
