/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	kotsv1beta1 "github.com/replicatedhq/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LintConfigsGetter has a method to return a LintConfigInterface.
// A group's client should implement this interface.
type LintConfigsGetter interface {
	LintConfigs(namespace string) LintConfigInterface
}

// LintConfigInterface has methods to work with LintConfig resources.
type LintConfigInterface interface {
	Create(ctx context.Context, lintConfig *kotsv1beta1.LintConfig, opts v1.CreateOptions) (*kotsv1beta1.LintConfig, error)
	Update(ctx context.Context, lintConfig *kotsv1beta1.LintConfig, opts v1.UpdateOptions) (*kotsv1beta1.LintConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lintConfig *kotsv1beta1.LintConfig, opts v1.UpdateOptions) (*kotsv1beta1.LintConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kotsv1beta1.LintConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*kotsv1beta1.LintConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kotsv1beta1.LintConfig, err error)
	LintConfigExpansion
}

// lintConfigs implements LintConfigInterface
type lintConfigs struct {
	*gentype.ClientWithList[*kotsv1beta1.LintConfig, *kotsv1beta1.LintConfigList]
}

// newLintConfigs returns a LintConfigs
func newLintConfigs(c *KotsV1beta1Client, namespace string) *lintConfigs {
	return &lintConfigs{
		gentype.NewClientWithList[*kotsv1beta1.LintConfig, *kotsv1beta1.LintConfigList](
			"lintconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kotsv1beta1.LintConfig { return &kotsv1beta1.LintConfig{} },
			func() *kotsv1beta1.LintConfigList { return &kotsv1beta1.LintConfigList{} },
		),
	}
}
