/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	kotsv1beta1 "github.com/replicatedhq/kotskinds/apis/kots/v1beta1"
	scheme "github.com/replicatedhq/kotskinds/client/kotsclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TerraformsGetter has a method to return a TerraformInterface.
// A group's client should implement this interface.
type TerraformsGetter interface {
	Terraforms(namespace string) TerraformInterface
}

// TerraformInterface has methods to work with Terraform resources.
type TerraformInterface interface {
	Create(ctx context.Context, terraform *kotsv1beta1.Terraform, opts v1.CreateOptions) (*kotsv1beta1.Terraform, error)
	Update(ctx context.Context, terraform *kotsv1beta1.Terraform, opts v1.UpdateOptions) (*kotsv1beta1.Terraform, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, terraform *kotsv1beta1.Terraform, opts v1.UpdateOptions) (*kotsv1beta1.Terraform, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kotsv1beta1.Terraform, error)
	List(ctx context.Context, opts v1.ListOptions) (*kotsv1beta1.TerraformList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kotsv1beta1.Terraform, err error)
	TerraformExpansion
}

// terraforms implements TerraformInterface
type terraforms struct {
	*gentype.ClientWithList[*kotsv1beta1.Terraform, *kotsv1beta1.TerraformList]
}

// newTerraforms returns a Terraforms
func newTerraforms(c *KotsV1beta1Client, namespace string) *terraforms {
	return &terraforms{
		gentype.NewClientWithList[*kotsv1beta1.Terraform, *kotsv1beta1.TerraformList](
			"terraforms",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kotsv1beta1.Terraform { return &kotsv1beta1.Terraform{} },
			func() *kotsv1beta1.TerraformList { return &kotsv1beta1.TerraformList{} },
		),
	}
}
